# Generated by Django 4.0.4 on 2022-05-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('country', models.CharField(default=None, max_length=100)),
                ('address', models.CharField(default=None, max_length=100)),
                ('city', models.CharField(default=None, max_length=100)),
                ('postcode', models.CharField(default=None, max_length=100)),
                ('image', models.CharField(default=None, max_length=250)),
                ('website', models.CharField(default=None, max_length=200)),
                ('email', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('number', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('google_directions_link', models.CharField(default=None, max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
