# Generated by Django 4.0.4 on 2022-05-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='number',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
