# Generated by Django 4.0.4 on 2022-04-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfspots', '0002_alter_surfspot_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfspot',
            name='image',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='magic_seaweed_link',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
