# Generated by Django 4.0.4 on 2022-04-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfspots', '0003_alter_surfspot_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfspot',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='country',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='postcode',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
