# Generated by Django 4.0.4 on 2022-04-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('surfspots', '0004_alter_surfspot_address_alter_surfspot_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfspot',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='surfspot',
            name='restaurants_nearby',
            field=models.ManyToManyField(blank=True, related_name='surfspots_nearby', to='restaurants.restaurant'),
        ),
    ]
