# Generated by Django 4.0.4 on 2022-05-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfspots', '0005_surfspot_city_surfspot_restaurants_nearby'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfspot',
            name='google_directions_link',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
