# Generated by Django 4.0.4 on 2022-05-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfspots', '0006_surfspot_google_directions_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfspot',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default='0', max_digits=9),
        ),
        migrations.AddField(
            model_name='surfspot',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default='0', max_digits=9),
        ),
    ]
